name: PixLit
options:
  bundleIdPrefix: com.pixlit
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  PixLit:
    type: application
    platform: macOS
    sources:
      - path: PixLit
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pixlit.app
        INFOPLIST_FILE: PixLit/Info.plist
        CODE_SIGN_ENTITLEMENTS: PixLit/PixLit.entitlements
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: PixLit
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - sdk: Vision.framework
      - sdk: Carbon.framework
